# Generated by Django 3.0.5 on 2020-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='bike_needed',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='car_needed',
        ),
        migrations.AddField(
            model_name='contact',
            name='vehicle',
            field=models.CharField(default='', max_length=5),
        ),
    ]
