# Generated by Django 3.0.5 on 2020-04-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200427_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='required_date_time',
            new_name='time',
        ),
    ]
