# Generated by Django 3.0.5 on 2020-04-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200427_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='listing_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
