# Generated by Django 3.0.5 on 2020-04-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('address', models.CharField(max_length=350)),
                ('contact_number', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('opening_time', models.CharField(max_length=1000)),
                ('closing_time', models.CharField(max_length=1000)),
                ('area_in_acres', models.DecimalField(decimal_places=1, max_digits=6)),
                ('Numbers_of_bikes', models.IntegerField()),
                ('Numbers_of_cars', models.IntegerField()),
                ('main_image', models.ImageField(default='', upload_to='main_image/%Y%m%d')),
                ('image1', models.ImageField(blank=True, upload_to='image1/%Y%m%d')),
                ('image2', models.ImageField(blank=True, upload_to='image2/%Y%m%d')),
                ('image3', models.ImageField(blank=True, upload_to='image3/%Y%m%d')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('price_of_bikes_per_hour', models.IntegerField()),
                ('price_of_cars_per_hour', models.IntegerField()),
                ('parking_available', models.BooleanField(default=False)),
            ],
        ),
    ]
