# Generated by Django 3.0.5 on 2020-04-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='email',
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
